REVIEWED_BY = "Convertor4U Editorial Team"
REVIEWED_ON = "2026-08-16"


def faq(question, answer):
    return {"question": question, "answer": answer}


GUIDES = {
    "length": {
        "guide_intro": "Length describes one-dimensional distance. Metric units scale by powers of ten, while international inches, feet, yards, and miles are linked to the meter by exact definitions. A nautical mile is exactly 1,852 meters and is designed for navigation rather than ordinary road distance.",
        "real_world_uses": "Millimeters suit manufacturing tolerances, centimeters suit small objects, and meters suit rooms and athletic distances. Kilometers and miles are common for travel. Feet and inches remain prominent in US construction and product dimensions, while nautical miles are standard in marine and aviation navigation.",
        "rounding_guidance": "Do not report more precision than the original measurement supports. Keep two extra digits during calculation, then round once at the end. Construction may need the nearest millimeter or fraction of an inch; route distances rarely need that precision.",
        "regional_notes": "Most countries use metric length units. US everyday measurements often use inches, feet, yards, and miles; UK road distances use miles even though metric units are common elsewhere. The converter uses international, not historical survey, definitions.",
        "common_mistakes": "Do not use a linear length factor for area or volume. Also distinguish the nautical mile from the statute mile and read decimal feet carefully: 5.5 ft means 5 ft 6 in, not 5 ft 5 in.",
        "faq": [faq("Is one inch exactly 2.54 centimeters?", "Yes. The international inch is exactly 25.4 millimeters, so it is exactly 2.54 centimeters."), faq("Why is a nautical mile longer than a mile?", "A nautical mile is fixed at 1,852 meters and relates to navigation; an international statute mile is exactly 1,609.344 meters."), faq("Should I round before converting?", "No. Convert using the available digits and round the final answer so early rounding does not accumulate error.")],
    },
    "mass": {
        "guide_intro": "Mass measures the amount of matter in an object. The kilogram is the SI base unit, and metric units scale by powers of ten. The international avoirdupois pound is exactly 0.45359237 kilograms; ounces and stones in this guide derive from that same system.",
        "real_world_uses": "Grams and kilograms are used for food, science, medicine, shipping, and body mass. Milligrams suit small quantities. Pounds and ounces are common in the United States, stone is still used informally for body mass in the United Kingdom, and tonnes describe large freight or industrial loads.",
        "rounding_guidance": "Match the result to the scale and quality of the measurement. A kitchen scale may justify whole grams, while freight may be rounded to kilograms. Keep guard digits for multi-step work and avoid presenting a converted value as more accurate than the source.",
        "regional_notes": "This category uses the international avoirdupois pound and ounce. It does not represent troy ounces used for precious metals. A metric tonne is 1,000 kilograms and is not the same as a US short ton or Imperial long ton.",
        "common_mistakes": "Mass and force are different quantities. A kilogram is not a newton or kilogram-force. Also check whether an unlabeled 'ounce' means avoirdupois mass, fluid volume, or troy mass before converting.",
        "faq": [faq("How many ounces are in an avoirdupois pound?", "There are exactly 16 avoirdupois ounces in one international avoirdupois pound."), faq("Is a tonne the same as a ton?", "Not necessarily. A metric tonne is 1,000 kg; US short tons and Imperial long tons are different."), faq("Why is weight listed under mass?", "Everyday speech often says weight for mass. The converter's kg, g, lb, oz, and stone entries are mass units; force units are in the Force category.")],
    },
    "temperature": {
        "guide_intro": "Temperature conversions require both a scale ratio and an offset. Celsius and kelvin have equal-sized intervals, but their zero points differ by exactly 273.15. Fahrenheit and Rankine intervals are five-ninths of a kelvin, with different zero points.",
        "real_world_uses": "Celsius is widely used for weather, cooking, and daily life. Fahrenheit remains common for US weather and ovens. Kelvin is used for thermodynamic and scientific work, while Rankine appears in some US engineering calculations involving absolute temperature.",
        "rounding_guidance": "Weather and room temperatures usually need no more than one decimal place. Laboratory work should follow instrument uncertainty. Preserve the offset calculation before rounding; rounding the intermediate Celsius or kelvin value can shift the final answer.",
        "regional_notes": "Most countries report everyday temperature in Celsius, while the United States commonly uses Fahrenheit. Scientific standards use kelvin without the degree sign. Recipe temperatures must be checked for both scale and oven behavior.",
        "common_mistakes": "Do not convert Celsius and Fahrenheit by multiplying alone—the offset matters. Absolute temperatures cannot be below 0 K or 0 °R, and a temperature difference is converted differently from a temperature reading with a zero point.",
        "faq": [faq("Why does 0 °C not convert to 0 °F?", "The scales have different zero points: 0 °C equals 32 °F."), faq("Is a change of 1 °C equal to a change of 1 K?", "Yes. Celsius and kelvin intervals are the same size, though their scale readings have different zero points."), faq("Can kelvin be negative?", "Ordinary thermodynamic temperature on the kelvin scale cannot be below absolute zero, 0 K.")],
    },
    "area": {
        "guide_intro": "Area measures a two-dimensional surface. Square units come from applying a length unit in two perpendicular directions, so conversion factors are squared. One square foot, for example, is exactly 0.09290304 square meter—not 0.3048 square meter.",
        "real_world_uses": "Square meters and square feet describe rooms and buildings. Square kilometers describe regions. Acres and hectares are common for land, agriculture, and property listings, while square inches suit small surfaces and material specifications.",
        "rounding_guidance": "Property and planning figures may be rounded to whole square units, but material estimates should retain enough precision before adding a separate waste allowance. Never hide measurement uncertainty behind many converted decimal places.",
        "regional_notes": "Hectares and square meters dominate metric land measurement. Acres remain common in the United States, United Kingdom, and several other countries. Property conventions and legal survey records vary, so use the unit stated in the governing document.",
        "common_mistakes": "The most frequent error is using a length factor without squaring it. Another is confusing hectare and square kilometer: one square kilometer contains 100 hectares.",
        "faq": [faq("Why is the area factor squared?", "Area has two length dimensions. Both dimensions must be converted, so the linear factor is applied twice."), faq("How many square meters are in a hectare?", "A hectare is exactly 10,000 square meters."), faq("Is an acre a square shape?", "No. An acre specifies area only and can have many shapes.")],
    },
    "volume": {
        "guide_intro": "Volume measures three-dimensional space or liquid capacity. Metric liters connect directly to cubic measure: one liter is exactly one cubic decimeter and one cubic meter is exactly 1,000 liters. US liquid units in this category use their exact US definitions.",
        "real_world_uses": "Milliliters suit medicine and small containers, liters suit beverages and fuel, and cubic meters suit tanks, rooms, and utility usage. US gallons, quarts, cups, and fluid ounces remain common on American products and recipes.",
        "rounding_guidance": "For packaging, round to the labeled container precision. Laboratory and dosing work must follow calibrated equipment and required tolerances. Keep full precision during the conversion and round only after the final unit is chosen.",
        "regional_notes": "A US liquid gallon is not an Imperial gallon, and their fluid ounces differ. Every customary entry here is labeled as US where ambiguity matters; the plain fluid-ounce entry uses the US liquid definition.",
        "common_mistakes": "Do not treat volume and mass as interchangeable: a liter of one material need not weigh a kilogram. Also cube linear factors when converting cubic dimensions rather than using the length factor once.",
        "faq": [faq("Is one milliliter equal to one cubic centimeter?", "Yes. One milliliter is exactly one cubic centimeter."), faq("Are US and Imperial gallons equal?", "No. They are different sizes, so the regional system must be identified."), faq("Can liters be converted directly to kilograms?", "Only when the material's density is known; liters measure volume and kilograms measure mass.")],
    },
    "time": {
        "guide_intro": "Time conversion is straightforward for fixed durations: a minute is 60 seconds, an hour is 3,600 seconds, and a day in this calculator is 86,400 seconds. The listed year is explicitly a fixed 365-day duration, not a variable calendar calculation.",
        "real_world_uses": "Milliseconds suit software and timing, minutes and hours suit daily schedules, and days or weeks suit projects and travel. Fixed-duration conversions are useful for elapsed time, billing, experiments, and media lengths.",
        "rounding_guidance": "For schedules, round to a practical minute only after converting. Scientific timing should follow the clock's resolution. Decimal hours are not hours-and-minutes notation: 1.5 hours is 1 hour 30 minutes.",
        "regional_notes": "Clock formats vary, but these unit durations do not. Civil days can be affected by daylight-saving changes, and calendar years can contain 365 or 366 days; those calendar effects are outside a fixed-duration converter.",
        "common_mistakes": "Do not assume every calendar month has the same duration or every civil day has exactly 24 local-clock hours. Read the 'Year (365 days)' label before using the result for dates.",
        "faq": [faq("Does this converter account for leap years?", "No. Its year unit is explicitly fixed at 365 days."), faq("Is 1.25 hours 1 hour 25 minutes?", "No. The decimal part is a fraction of an hour; 0.25 hour equals 15 minutes."), faq("Why can a calendar day differ from 24 hours?", "Local clock changes such as daylight saving can create 23- or 25-hour civil days, even though the fixed duration here is 86,400 seconds.")],
    },
    "speed": {
        "guide_intro": "Speed is distance traveled per unit time. The converter expresses each unit through meters per second, preserving exact international length definitions and fixed time relationships. A knot is one nautical mile per hour.",
        "real_world_uses": "Kilometers per hour and miles per hour are common for roads, meters per second for science and athletics, feet per second for some engineering work, and knots for ships, aircraft, and wind in navigation contexts.",
        "rounding_guidance": "Road and weather readings usually need whole units; engineering values may need more. Converted precision should not exceed the measuring device. Keep extra digits if speed feeds a later distance or time calculation.",
        "regional_notes": "Road signs use km/h in most countries and mph in the United States and United Kingdom. Maritime and aviation operations use knots internationally. Confirm the unit rather than inferring it from the number alone.",
        "common_mistakes": "A knot is not a kilometer per hour or mile per hour. Also, speed is a magnitude, while velocity includes direction; converting units does not preserve missing directional information.",
        "faq": [faq("What is a knot?", "One knot is one nautical mile per hour, exactly 1.852 km/h."), faq("Why is mph to km/h not a round factor?", "The international mile is exactly 1,609.344 m, producing 1 mph = 1.609344 km/h."), faq("Are speed and velocity identical?", "They share units, but velocity also includes direction.")],
    },
    "pressure": {
        "guide_intro": "Pressure is force distributed over area. The SI pascal equals one newton per square meter. Kilopascals, bar, standard atmosphere, psi, and millimeters of mercury are common in different scientific, weather, medical, automotive, and industrial settings.",
        "real_world_uses": "Tire pressures often use psi, bar, or kPa. Weather reports use hPa or related units, process systems use bar and kPa, and some clinical readings use mmHg. Standard atmosphere is useful as a reference condition.",
        "rounding_guidance": "Round to the gauge or specification resolution, not the calculator's maximum display. Safety limits require the tolerance and calibration stated by the manufacturer. Retain guard digits in engineering calculations.",
        "regional_notes": "Tire labels may show several equivalent units. Psi is common in the United States and United Kingdom, while bar and kPa are widespread elsewhere. Medical conventions often retain mmHg.",
        "common_mistakes": "Gauge pressure is relative to ambient pressure; absolute pressure is relative to a vacuum. Unit conversion does not change one reference type into the other unless atmospheric pressure is explicitly added or removed.",
        "faq": [faq("What does one pascal mean?", "One pascal is one newton of force distributed over one square meter."), faq("Are bar and atmosphere the same?", "No. One bar is exactly 100,000 Pa, while one standard atmosphere is exactly 101,325 Pa."), faq("Can I convert gauge pressure directly to absolute pressure?", "Not with a unit factor alone; you must also know and apply the relevant ambient pressure.")],
    },
    "currency": {
        "guide_intro": "Currency conversion differs from physical-unit conversion because exchange rates change. Convertor4U retrieves dated institutional reference rates, caches them for reliability, and labels stale fallback data. Results are estimates for comparison, not executable buy or sell quotes.",
        "real_world_uses": "Reference conversions help compare prices, plan travel, review invoices, and estimate budgets. The amount charged by a bank, card network, cash exchange, or payment service can differ because of timing, spreads, commissions, and taxes.",
        "rounding_guidance": "Use the currency's normal minor unit for a simple estimate, commonly two decimal places, but keep more digits during totals. Some currencies use different minor-unit conventions. Always use the final provider quote for payment or accounting.",
        "regional_notes": "The same dollar or pound word can refer to different currencies, so use ISO codes such as USD, AUD, CAD, NZD, or GBP. Market availability and business days affect the date of reference data.",
        "common_mistakes": "Do not treat the displayed midpoint-style reference rate as a guaranteed customer rate. Check the rate date, ISO currency code, provider fees, card markup, and whether the quote direction has been reversed.",
        "faq": [faq("How live are the currency rates?", "The page shows the rate date returned by the provider. Reference data may remain on the latest business day during weekends or holidays."), faq("Will my bank give the same result?", "Not necessarily. Banks and payment services may use different times, spreads, and fees."), faq("Why use ISO currency codes?", "Codes distinguish currencies with similar names or symbols, such as USD, CAD, AUD, and NZD.")],
    },
    "energy": {
        "guide_intro": "Energy measures the capacity to do work or transfer heat. The joule is the SI unit. Kilowatt-hours describe energy accumulated from power over time, calories and kilocalories describe heat or food energy, and BTU remains common in heating and cooling contexts.",
        "real_world_uses": "Electricity bills use kWh, batteries may use Wh, nutrition labels use kilocalories or kilojoules, heating equipment uses BTU, and physics uses joules or electronvolts depending on scale.",
        "rounding_guidance": "Billing and nutrition should follow the precision of the original label. Scientific work should preserve significant figures. Small electronvolt values converted to joules may be clearer in scientific notation.",
        "regional_notes": "Food labels may write 'Calories' with a capital C to mean kilocalories. Kilojoules are prominent on labels in many countries, while food Calories are common in the United States. BTU conventions can vary slightly; this site states its stored factor.",
        "common_mistakes": "A watt is power, not energy. Multiply power by time to obtain Wh or joules. Also distinguish the small calorie from the nutritional kilocalorie, which is 1,000 small calories.",
        "faq": [faq("Is a food Calorie a kilocalorie?", "Yes. In nutrition, one capital-C Calorie normally means one kilocalorie, or 4,184 joules."), faq("How is kWh related to kW?", "Energy equals power multiplied by time; using 1 kW for 1 hour consumes 1 kWh."), faq("Why use electronvolts?", "Electronvolts give convenient-sized numbers for atomic and particle-scale energies.")],
    },
    "power": {
        "guide_intro": "Power is the rate at which energy is transferred or work is done. One watt is one joule per second. Kilowatts and megawatts scale that rate, while horsepower, BTU per hour, and foot-pounds per second reflect mechanical or heating traditions.",
        "real_world_uses": "Appliances and solar panels use watts or kilowatts, power stations use megawatts, engines and motors may use horsepower, and heating or cooling specifications often use BTU per hour.",
        "rounding_guidance": "Nameplate power is often a rated or nominal value, so extra converted digits add no certainty. For energy planning, retain sufficient precision until power is multiplied by operating time and efficiency.",
        "regional_notes": "Mechanical horsepower and metric horsepower are different units; both are included and clearly labeled. Vehicle markets may advertise hp, PS, or kW depending on country and convention.",
        "common_mistakes": "Do not confuse power with energy. A 2 kW heater describes its rate; energy consumption depends on how long it operates. Check whether 'horsepower' means mechanical or metric horsepower.",
        "faq": [faq("What is the difference between kW and kWh?", "kW measures power; kWh measures energy accumulated over time."), faq("Are hp and PS identical?", "No. Mechanical horsepower is about 745.7 W, while metric horsepower is about 735.5 W."), faq("Does rated power equal actual consumption?", "Not always. Operating mode, load, duty cycle, and efficiency can change actual power and energy use.")],
    },
    "force": {
        "guide_intro": "Force changes an object's motion or deformation. The SI newton is the force that accelerates one kilogram at one meter per second squared. Pound-force and kilogram-force use defined standard-gravity relationships; dyne and poundal arise from other coherent systems.",
        "real_world_uses": "Newtons and kilonewtons appear in structures, testing, mechanics, and fastener specifications. Pound-force and kip are common in US engineering. Kilogram-force appears on some older equipment and product ratings.",
        "rounding_guidance": "Engineering results must follow the input load accuracy, applicable safety factors, and design code. Do not round intermediate load combinations aggressively, and never infer a safe working load solely from a unit conversion.",
        "regional_notes": "SI engineering uses N and kN. US documents may use lbf or kip. The symbols lb and lbf should not be treated as interchangeable because one commonly denotes mass and the other force.",
        "common_mistakes": "Mass is not force. Converting kilograms to newtons requires a gravitational acceleration assumption, whereas kilogram-force is already defined using standard gravity. Real local weight can differ slightly with gravity.",
        "faq": [faq("What is one newton?", "It is the force required to accelerate 1 kg at 1 m/s²."), faq("Is kilogram-force the same as kilogram?", "No. Kilogram is mass; kilogram-force is a force equal to 9.80665 N."), faq("What is a kip?", "A kip-force is 1,000 pounds-force and is common in US structural engineering.")],
    },
    "angle": {
        "guide_intro": "Plane angle describes rotation between two directions. A full revolution is 360 degrees, 400 gradians, or 2π radians. Arcminutes and arcseconds subdivide a degree for navigation and astronomy, while milliradians are useful for small angles.",
        "real_world_uses": "Degrees suit everyday geometry and bearings, radians suit mathematics and physics, gradians appear in some surveying, and arcminutes or arcseconds describe fine coordinates. Milliradians appear in optics, engineering, and ranging.",
        "rounding_guidance": "Small angular errors can produce large position errors over distance. Preserve sufficient digits for navigation or machining, and round only to the instrument's angular resolution. Decimal degrees and degrees-minutes-seconds require separate formatting steps.",
        "regional_notes": "Degrees are widely understood, while mathematical formulas often require radians. The word 'mil' is ambiguous across military and engineering angular systems; this converter provides the SI milliradian and labels it mrad.",
        "common_mistakes": "Do not feed degree values into software that expects radians. Also, 12.5 degrees means 12 degrees 30 arcminutes, not 12 degrees 5 arcminutes.",
        "faq": [faq("Why do formulas often use radians?", "Radians connect angle directly to arc length and make many calculus relationships work without extra constants."), faq("How many radians are in a full turn?", "A full revolution is exactly 2π radians."), faq("Is a milliradian always the same as a military mil?", "No. Several mil conventions exist; this converter's mrad is exactly one-thousandth of a radian.")],
    },
    "fuel-economy": {
        "guide_intro": "Fuel economy can express distance per fuel volume, such as km/L or mpg, or fuel volume per distance, such as L/100 km. These directions are reciprocal: better efficiency gives a higher mpg or km/L value but a lower L/100 km value.",
        "real_world_uses": "Drivers use these conversions to compare vehicle specifications, estimate trip fuel, and interpret imported reviews. Real consumption changes with speed, traffic, weather, load, tires, terrain, and driving style.",
        "rounding_guidance": "One decimal place is usually adequate for vehicle comparisons. Keep more digits when estimating total trip fuel, then round to a practical volume. Published test-cycle numbers are standardized estimates, not guarantees.",
        "regional_notes": "US mpg and Imperial mpg use different gallons. The same numeric mpg therefore represents different efficiency. L/100 km is common in Europe and many other regions, while the US commonly uses mpg.",
        "common_mistakes": "Do not convert L/100 km with a simple multiplication factor; it requires division. Zero consumption is not a valid denominator, and US mpg must not be substituted for Imperial mpg.",
        "faq": [faq("Why does lower L/100 km mean better economy?", "It measures fuel consumed for a fixed distance, so using fewer liters is more efficient."), faq("Are US mpg and Imperial mpg equal?", "No. The Imperial gallon is larger, so the numeric mpg values differ for the same vehicle efficiency."), faq("Why is zero invalid in a reciprocal conversion?", "The reciprocal formula would divide by zero, which has no finite result.")],
    },
    "data-storage": {
        "guide_intro": "Digital information begins with the bit; one byte contains eight bits. Decimal prefixes use powers of 1,000, so one kilobyte is 1,000 bytes. IEC binary prefixes use powers of 1,024, so one kibibyte is 1,024 bytes.",
        "real_world_uses": "Storage manufacturers commonly label disks in decimal GB or TB. Operating systems and memory tools may show binary GiB or MiB. Network speeds are often stated in bits per second, while file sizes are usually shown in bytes.",
        "rounding_guidance": "Keep enough precision to explain capacity differences, but whole MB or GB often suffice for user-facing estimates. Transfer-time calculations also need protocol overhead and actual throughput, not only a storage-unit conversion.",
        "regional_notes": "These are international technical conventions rather than regional units. Usage is inconsistent, however: some interfaces display a binary quantity but label it GB instead of GiB. Check the stated prefix definition.",
        "common_mistakes": "Capital B means byte and lowercase b means bit. Do not assume MB equals MiB or GB equals GiB, and do not divide a file size in bytes by a network rate in bits per second without converting the bit/byte relationship.",
        "faq": [faq("How many bits are in a byte?", "A byte contains eight bits."), faq("What is the difference between GB and GiB?", "GB is decimal: 1,000,000,000 bytes. GiB is binary: 1,073,741,824 bytes."), faq("Why does a drive appear smaller in some software?", "The label may use decimal capacity while the software reports a binary quantity, and formatting or system data may also occupy space.")],
    },
    "cooking": {
        "guide_intro": "This cooking converter handles volume, not ingredient mass. Metric milliliters and liters are unambiguous, while cups, tablespoons, teaspoons, pints, and fluid ounces vary by regional system. The customary entries here are explicitly US measures unless labeled metric.",
        "real_world_uses": "Use these units to adapt recipes, scale batches, compare measuring tools, or interpret packaging. For baking, weighing ingredients is often more repeatable than measuring volume because packing and particle size affect a cup measurement.",
        "rounding_guidance": "Round to a measure you can reproduce: a sensible fraction of a spoon, a whole milliliter, or the resolution of a kitchen scale. For very small quantities, avoid converting to an impractically tiny cup fraction.",
        "regional_notes": "A US cup is about 236.588 mL; a metric cup is 250 mL. Australian tablespoon conventions can differ from the US value, and Imperial fluid measures differ from US measures. Always identify the recipe's origin.",
        "common_mistakes": "A cup of flour and a cup of water have the same volume but not the same mass. Do not convert volume to grams without an ingredient-specific density or tested recipe chart, and do not assume every country's tablespoon is identical.",
        "faq": [faq("Is a metric cup the same as a US cup?", "No. This converter defines a metric cup as 250 mL and a US cup as exactly 236.5882365 mL."), faq("Can I convert cups of flour to grams here?", "Not reliably with volume alone; flour mass depends on density, packing, and technique."), faq("Why label tablespoons as US?", "Tablespoon volumes vary by convention, so the label prevents an ambiguous conversion.")],
    },
    "frequency": {
        "guide_intro": "Frequency counts repeating events per unit time. One hertz is one cycle per second. Kilohertz, megahertz, and gigahertz are decimal multiples. Revolutions per minute and beats per minute count events per minute, while radians per second describes angular frequency.",
        "real_world_uses": "Hertz appears in audio and mains electricity, MHz and GHz in radio and processors, rpm in rotating machinery, bpm in music and heart-rate displays, and rad/s in physics and control engineering.",
        "rounding_guidance": "Use the resolution of the measuring instrument or specification. Audio and radio values may be rounded for labels, while control-system calculations may require additional digits for phase and timing work.",
        "regional_notes": "Electrical mains frequency is commonly 50 or 60 Hz depending on the grid, but that is a system property rather than a unit difference. SI prefixes remain consistent internationally.",
        "common_mistakes": "A revolution or cycle must be defined consistently. Angular frequency in rad/s is not numerically equal to cyclic frequency in Hz; divide by 2π. Do not confuse MHz frequency with data transfer in Mb/s.",
        "faq": [faq("How do rpm and hertz relate?", "Divide rpm by 60 to obtain revolutions per second, expressed in hertz when one revolution is one cycle."), faq("Is rad/s the same as Hz?", "No. Angular frequency in rad/s equals 2π times cyclic frequency in Hz."), faq("Does a higher processor GHz always mean a faster computer?", "No. Frequency is only one factor; architecture, workload, cores, memory, and power limits also matter.")],
    },
}

FEATURED_PAIRS = {
    "length": [("cm", "inches"), ("meter", "foot"), ("kilometer", "mile"), ("mile", "kilometer")],
    "mass": [("kilogram", "pound"), ("pound", "kilogram"), ("ounce", "gram")],
    "temperature": [("celsius", "fahrenheit"), ("fahrenheit", "celsius"), ("kelvin", "celsius")],
    "area": [("square-meter", "square-foot"), ("acre", "hectare"), ("hectare", "acre")],
    "volume": [("liter", "us-gallon"), ("us-gallon", "liter"), ("milliliter", "fluid-ounce")],
    "time": [("hour", "minute"), ("day", "hour"), ("week", "day")],
    "speed": [("kilometer-per-hour", "mile-per-hour"), ("mile-per-hour", "kilometer-per-hour"), ("knot", "kilometer-per-hour")],
    "pressure": [("psi", "kilopascal"), ("bar", "psi"), ("atmosphere", "pascal")],
    "currency": [("usd", "zar"), ("eur", "usd"), ("gbp", "usd"), ("zar", "usd")],
    "energy": [("kilowatt-hour", "joule"), ("kilocalorie", "kilojoule"), ("btu", "joule")],
    "power": [("kilowatt", "horsepower"), ("horsepower", "kilowatt"), ("watt", "btu-per-hour")],
    "force": [("newton", "pound-force"), ("kilogram-force", "newton"), ("pound-force", "newton")],
    "angle": [("degree", "radian"), ("radian", "degree"), ("degree", "gradian")],
    "fuel-economy": [("liters-per-100km", "mile-per-us-gallon"), ("mile-per-us-gallon", "liters-per-100km"), ("kilometer-per-liter", "mile-per-us-gallon")],
    "data-storage": [("byte", "bit"), ("gigabyte", "gibibyte"), ("megabyte", "mebibyte")],
    "cooking": [("us-cup", "milliliter"), ("us-tablespoon", "milliliter"), ("metric-cup", "us-cup")],
    "frequency": [("hertz", "revolution-per-minute"), ("revolution-per-minute", "hertz"), ("kilohertz", "megahertz")],
}
